server:
  port: 80

spring:
  application:
    name: cloud-consul-order-service

  cloud:
    consul:
      host: 192.168.137.110
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: 192.168.1.8