server:
  port: 84

spring:
  application:
    name: nacos-payment-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.110:3333,192.168.137.110:4444,192.168.137.110:5555
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080  # sentinel dashboard的路径
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.137.110:3333,192.168.137.110:4444,192.168.137.110:5555
            dataid: ${spring.application.name}
            groupid: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

#对Feign的支持
feign:
  sentinel:
    enabled: true