server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_route #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE  #通过微服务名实现动态路由
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由

        - id: payment_route2
          uri: http://localhost:8001
          predicates:
            - Path=/payment/discovery  #断言,路径相匹配的进行路由


        - id: route_guoji #路由的ID，没有固定规则但要求唯一，建议配合服务名      http://news.baidu.com/guoji
          #uri: http://news.baidu.com   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE   #通过微服务名实现动态路由
          predicates:
            - Path=/guoji   #断言,路径相匹配的进行路由

        - id: route_guonei
          uri: http://news.baidu.com
          predicates:
            - Path=/guonei  #断言,路径相匹配的进行路由
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
    instance-id: gateway9527
    prefer-ip-address: true
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka