server:
  port: 83

spring:
  application:
    name: nacos-payment-consumer

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.137.110:3333,192.168.137.110:4444,192.168.137.110:5555

management:
  endpoints:
    web:
      exposure:
        include: '*'